import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { Header } from "@/ui/Header";
import { Footer } from "@/ui/Footer";

export const metadata = {
  title: "Aizy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
